navbar-links:
    Archive: /archives
    Github: 'https://github.com/glnro'
    Work: 'https://fierce-woodland-24308.herokuapp.com'

avatar: /img/white_oroboro.png
favicon: /img/oroboro.png
titleimage: /img/full_name_white.png

header:
    title: "SAYING THINGS ON THE INTERNET!"
    motto:
    bigimgs:
        - src: /img/swarm_illustrator-01.png



googlefonts:
  - "Lora:400,700,400italic,700italic"
  - "Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800"

highlight:
  enable: true
# or use any highlight.js style
#  style_path: "//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.5.0/styles/default.min.css"
  style_path: "/css/highlight.css"

footer:
  github:
    link: 'https://github.com/glnro'
    title: GitHub
    icon: fa-github
    enable: true
  twitter:
    link: 'https://twitter.com/_Gallinaro'
    title: Twitter
    icon: fa-twitter
    enable: true
  linkin:
    link: 'https://www.linkedin.com/in/lgallinaro'
    title: LinkedIn
    icon: fa-linkedin
    enable: true

google_analytics:

comment:
  enable: false
